import React, { useState } from 'react';
import { X, Sparkles, Wand2, Rocket, Layers, Code, Globe, AlertCircle, Loader2 } from 'lucide-react';

export const CreateProjectModal = ({ isOpen, onClose, onCreateProject, showToast }) => {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [requirement, setRequirement] = useState('');
  const [domain, setDomain] = useState('E-commerce');
  const [targetPlatform, setTargetPlatform] = useState('Web + Mobile');
  const [techStack, setTechStack] = useState('Node.js');
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  if (!isOpen) return null;

  const handleExampleInsert = (type) => {
    if (type === 'food') {
      setName('Online Food Delivery System');
      setDescription('An online platform connecting customers, restaurants and delivery partners with live GPS tracking.');
      setRequirement('I want to build an online food delivery system where customers can browse restaurants, view menus, place food orders, make payments and track deliveries in real time. Restaurants should manage their menu items and process incoming orders. Delivery partners should receive delivery assignments and update delivery status.');
      setDomain('E-commerce');
      setTargetPlatform('Web + Mobile');
      setTechStack('Node.js');
    } else if (type === 'college') {
      setName('College Management System');
      setDescription('Comprehensive enterprise ERP managing student registration, faculty schedules, and grade transcripts.');
      setRequirement('Build a college management system where students register for semester courses, view attendance, check examination results and pay fees. Faculty members record attendance, upload internal marks and manage course materials.');
      setDomain('Education');
      setTargetPlatform('Web');
      setTechStack('Java / Spring Boot');
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!name.trim() || !requirement.trim()) {
      showToast("Please enter project name and requirement details", "error");
      return;
    }

    setIsAnalyzing(true);
    setTimeout(() => {
      setIsAnalyzing(false);
      const newProj = {
        id: `proj-${Date.now()}`,
        name: name.trim(),
        description: description.trim() || 'Custom software requirement project generated by DevArchitect AI',
        domain,
        targetPlatform,
        techStack,
        lastUpdated: 'Just now',
        createdAt: new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
        progress: 90,
        status: 'Active',
        version: 'v1.0',
        rawRequirement: requirement.trim(),
        stats: {
          actors: 4,
          functionalRequirements: 14,
          nonFunctionalRequirements: 6,
          useCases: 10,
          entities: 7,
          apis: 12,
          architectureNodes: 6
        }
      };

      onCreateProject(newProj);
      onClose();
      showToast(`AI Analysis completed for "${newProj.name}"!`);
    }, 1500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-fade-in">
      <div className="w-full max-w-3xl bg-white border border-slate-200 rounded-3xl shadow-2xl overflow-hidden glass-panel flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50/60">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-indigo-600 to-indigo-500 flex items-center justify-center shadow-md shadow-indigo-500/20">
              <Wand2 className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900">Create New AI Architecture Project</h2>
              <p className="text-xs text-slate-500 font-medium">Describe your software idea in natural language to generate full design artifacts</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Quick presets helper */}
        <div className="bg-indigo-50/60 border-b border-indigo-100 px-6 py-2.5 flex items-center justify-between text-xs">
          <span className="text-indigo-900 font-bold flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 text-indigo-600" />
            Quick Example Prompts:
          </span>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => handleExampleInsert('food')}
              className="px-3 py-1 rounded-xl bg-white hover:bg-indigo-600 hover:text-white text-indigo-700 border border-indigo-200 shadow-2xs font-semibold transition-all text-xs"
            >
              🍔 Food Delivery System
            </button>
            <button
              type="button"
              onClick={() => handleExampleInsert('college')}
              className="px-3 py-1 rounded-xl bg-white hover:bg-indigo-600 hover:text-white text-indigo-700 border border-indigo-200 shadow-2xs font-semibold transition-all text-xs"
            >
              🎓 College ERP System
            </button>
          </div>
        </div>

        {/* Form body */}
        <form onSubmit={handleSubmit} className="p-6 overflow-y-auto space-y-4 flex-1">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Project Name <span className="text-indigo-600">*</span>
              </label>
              <input
                type="text"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="e.g. Online Food Delivery System"
                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3.5 py-2 text-xs text-slate-900 placeholder-slate-400 focus:outline-none focus:bg-white focus:border-indigo-600 focus:ring-2 focus:ring-indigo-500/20"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Short Description
              </label>
              <input
                type="text"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="e.g. Platform connecting customers, restaurants & drivers"
                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3.5 py-2 text-xs text-slate-900 placeholder-slate-400 focus:outline-none focus:bg-white focus:border-indigo-600 focus:ring-2 focus:ring-indigo-500/20"
              />
            </div>
          </div>

          {/* Large Requirement Input */}
          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="block text-xs font-bold text-slate-700">
                Software Requirement Input (Natural Language) <span className="text-indigo-600">*</span>
              </label>
              <span className="text-[10px] text-slate-400 font-mono font-medium">{requirement.length} characters</span>
            </div>
            <textarea
              required
              rows={5}
              value={requirement}
              onChange={(e) => setRequirement(e.target.value)}
              placeholder="Describe what you want to build in plain English... e.g. I want to build an online food delivery system where customers can browse restaurants, order food, make payments and track delivery."
              className="w-full bg-slate-50 border border-slate-200 rounded-xl p-3 text-xs text-slate-900 placeholder-slate-400 focus:outline-none focus:bg-white focus:border-indigo-600 focus:ring-2 focus:ring-indigo-500/20 font-sans leading-relaxed"
            />
          </div>

          {/* Optional metadata selectors */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2 border-t border-slate-100">
            <div>
              <label className="block text-xs font-bold text-slate-600 mb-1 flex items-center gap-1.5">
                <Layers className="w-3.5 h-3.5 text-indigo-600" />
                Project Domain
              </label>
              <select
                value={domain}
                onChange={(e) => setDomain(e.target.value)}
                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-xs text-slate-800 font-medium focus:outline-none focus:border-indigo-600"
              >
                <option value="E-commerce">E-commerce / Logistics</option>
                <option value="Healthcare">Healthcare</option>
                <option value="Education">Education</option>
                <option value="Finance">Finance / Fintech</option>
                <option value="Social">Social Media</option>
                <option value="Other">Other</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-600 mb-1 flex items-center gap-1.5">
                <Globe className="w-3.5 h-3.5 text-indigo-600" />
                Target Platform
              </label>
              <select
                value={targetPlatform}
                onChange={(e) => setTargetPlatform(e.target.value)}
                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-xs text-slate-800 font-medium focus:outline-none focus:border-indigo-600"
              >
                <option value="Web + Mobile">Web + Mobile Apps</option>
                <option value="Web">Web Application Only</option>
                <option value="Mobile">Mobile Native Only</option>
                <option value="Desktop">Desktop Client</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-600 mb-1 flex items-center gap-1.5">
                <Code className="w-3.5 h-3.5 text-indigo-600" />
                Tech Preference
              </label>
              <select
                value={techStack}
                onChange={(e) => setTechStack(e.target.value)}
                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-xs text-slate-800 font-medium focus:outline-none focus:border-indigo-600"
              >
                <option value="Node.js">Node.js / Express / React</option>
                <option value="Java / Spring Boot">Java / Spring Boot / React</option>
                <option value="Python / FastAPI">Python / FastAPI / React</option>
                <option value=".NET Core">C# / .NET Core / React</option>
                <option value="No Preference">No Preference (Auto-select)</option>
              </select>
            </div>
          </div>
        </form>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-100 bg-slate-50/60 flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs text-slate-500 font-medium">
            <AlertCircle className="w-4 h-4 text-indigo-600" />
            <span>AI model generates requirements, UML, DB ERD & APIs</span>
          </div>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl text-xs font-bold text-slate-500 hover:text-slate-800 hover:bg-slate-100 transition-colors"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleSubmit}
              disabled={isAnalyzing}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shadow-md shadow-indigo-500/20 transition-all disabled:opacity-50"
            >
              {isAnalyzing ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin text-white" />
                  <span>Analyzing Requirements...</span>
                </>
              ) : (
                <>
                  <Rocket className="w-4 h-4" />
                  <span>Start Analysis</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
